# Generated by Django 5.1.6 on 2026-03-27 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_activity_attachment_auditlog_emaillog_emailtemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='first_contacted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='LeadScoreEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('delta', models.SmallIntegerField()),
                ('reason', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_events', to='leads.lead')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['lead', 'created_at'], name='leads_leads_lead_id_834940_idx'), models.Index(fields=['code'], name='leads_leads_code_c1679b_idx')],
                'constraints': [models.UniqueConstraint(fields=('lead', 'code'), name='uniq_lead_score_event_code')],
            },
        ),
    ]
